server:
  port: 8090

spring:
  application:
    name: plazoleta-users-ms
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_users
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

microservices:
  plazoleta:
    url: http://localhost:8091

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-millis: ${JWT_EXPIRATION_MILLIS:300000}